## versions ##
[versions]
## SDK
minSdk = "23"
targetSdk = "33"
compileSdk = "33"
## Debug
debugVersionCode = "1"
debugVersionName = "1.0.0"
## App
gradle = "7.4.1"
kotlin = "1.8.0"
## Desugar
desugar = "1.1.5"
## Kotlin
core = "1.9.0"
coroutines = "1.6.3"
## Checks
detekt = "1.20.0"
ktlint = "3.5.0"
# checkstyle = "10.3"
gradlevers = "0.42.0"
## Android
appcompat = "1.6.1"
material = "1.8.0"
constraintlayout = "2.1.4"
recyclerview = "1.2.1"
swiperefreshlayout = "1.1.0"
activity = "1.6.1"
fragment = "1.5.5"
preference = "1.2.0"
lifecycle = "2.5.1"
navigation = "2.5.3"
parcelize = "1.4.30"
## Network
retrofit = "2.9.0"
okHttp = "4.10.0"
moshi = "1.14.0"
## ImageLoader
picasso = "2.71828"
glide = "4.13.2"
coil = "2.1.0"
## DI
hilt = "2.42"
koin = "3.3.2"
## Logs
timber = "5.0.1"
## Test
junit4 = "4.13.2"
mockito = "5.1.1"
extJunit = "1.1.5"
espresso = "3.5.1"
## Misc
splashscreen = "1.0.0-rc01"

## libraries ##
[libraries]
## Desugar
desugar = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar" }
## Kotlin
core = { module = "androidx.core:core-ktx", version.ref = "core" }
coroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutinesAndroid = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
## Android
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }
activity = { module = "androidx.activity:activity-ktx", version.ref = "activity" }
fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment" }
preference = { module = "androidx.preference:preference-ktx", version.ref = "preference" }
lifecycleRuntime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycleViewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
navigationFragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
navigationUi = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }
## Network
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofitConverterMoshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }
retrofitConverterGson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
okHttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okHttp" }
okHttpLogging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okHttp" }
moshi = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
moshiCodegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }
## ImageLoader
picasso = { module = "com.squareup.picasso:picasso", version.ref = "picasso" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glideCompiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }
coil = { module = "io.coil-kt:coil", version.ref = "coil" }
## DI
koin = { module = "io.insert-koin:koin-android", version.ref = "koin" }
## Logs
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
## Test
junit4 = { module = "junit:junit", version.ref = "junit4" }
mockito = { module = "org.mockito:mockito-core", version.ref = "mockito" }
extJunit = { module = "androidx.test.ext:junit", version.ref = "extJunit" }
espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
koinTest = { module = "io.insert-koin:koin-test", version.ref = "koin" }
koinJUnit4 = { module = "io.insert-koin:koin-test-junit4", version.ref = "koin" }
## Misc
splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "splashscreen" }

## bundles ##
[bundles]
## Android
android = ["appcompat", "material", "constraintlayout"]
lifecycle = ["lifecycleRuntime", "lifecycleViewmodel"]
navigation = ["navigationFragment", "navigationUi"]
## Network
retrofitMoshi = ["retrofit", "retrofitConverterMoshi", "okHttp", "okHttpLogging"]
retrofitGson = ["retrofit", "retrofitConverterGson", "okHttp", "okHttpLogging"]
## DI
koinTest = ["koinTest", "koinJUnit4"]

## plugins ##
[plugins]
## Android
androidApplication = { id = "com.android.application", version.ref = "gradle" }
androidLibrary = { id = "com.android.library", version.ref = "gradle" }
navigation = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navigation" }
parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "parcelize" }
## Kotlin
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
## Checks
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
ktlint = { id = "org.jmailen.kotlinter", version.ref = "ktlint" }
gradlevers = { id = "com.github.ben-manes.versions", version.ref = "gradlevers" }
## DI
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }